services:
  server:
    build:
      context: .
    env_file: .env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      - db
#      db:
#        condition: service_healthy
  db:
    image: mongo
    restart: always
    ports:
      - $DB_PORT:$DB_PORT
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
    volumes:
      - mongodb_data:/data/db
#    healthcheck:
#      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
volumes:
  mongodb_data:
