services:
  server:
    build:
      context: .
    env_file: .env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    networks:
      - my_network
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - $DB_PORT:$DB_PORT
    networks:
      - my_network
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
networks:
  my_network:
    driver: bridge
